spring.application.name=journal

# DATABASE DETAILS
spring.mongodb.uri=mongodb+srv://sumit_db:Sumit2032@cluster0.sh7vwua.mongodb.net/journaldb?appName=Cluster0
spring.mongodb.auto-index-creation=true

#Spring Security
spring.security.user.name=sumit
spring.security.user.password=sumit123
